version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run: sudo apt update; sudo apt install ruby-sass
      - run: sudo npm install uglify-js -g #TODO install locally and cache the dependency

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
          
      - run: cd www/ && composer install
      - run: mkdir www/css
      - run: sass --update resources/www/scss:www/css
      - run: python3 build/compile/minify.py

      - run: cp ~/repo ~/build-output -r

      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/build-output

  php-test:
    docker:
      - image: circleci/php:latest

    working_directory: ~/build-output

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          
      - run: php vendor/bin/phpunit --coverage-clover build/coverage/xml
      - run: php vendor/bin/codacycoverage clover build/coverage/xml

  python-test:
    machine:
      enabled: true

    working_directory: ~/build-output

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run: python2.7 ./build/tests/filenames.py www
      - run: python2.7 ./build/tests/existence.py www
      - run: sh ./build/tests/line-endings.sh

  deploy-testing:
    machine:
      enabled: true

    working_directory: ~/build-output

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

      - run: cd www/ && scp -oStrictHostKeyChecking=no -r * mentor@compcamps.com:/home/mentor/public_html/testing

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - php-test:
          requires:
            - build
      - python-test:
          requires:
            - build
      - deploy-testing:
          requires:
            - python-test
            - php-test
          filters:
            branches:
              only: master
