version: 2
jobs:
  build:
    docker:
      - image: circleci/php:latest-node-browsers

    working_directory: /tmp/project/

    steps:
      - checkout:
          path: /tmp/project/repo

      - run: sudo apt update; sudo apt install ruby-sass
      - run: sudo npm install uglify-js -g #TODO install locally and cache the dependency

      - run: cd /tmp/project/repo &&composer install -n --prefer-dist

      - run: cd /tmp/project/repo/www/ && composer install
      - run: mkdir /tmp/project/repo/www/css
      - run: cd /tmp/project/repo && sass --update resources/www/scss:www/css
      - run: python3 build/compile/minify.py
      - run: mkdir /tmp/project/workspace
      - run: cp /tmp/project/repo /tmp/project/workspace/build-output -r

      - persist_to_workspace:
          root: workspace
          paths:
            - build-output

  php-test:
    docker:
      - image: circleci/php:latest
      - image: circleci/mysql:5.6
        environment:
          - MYSQL_ROOT_PASSWORD=ubuntu
          - MYSQL_USER=ubuntu
          - MYSQL_PASSWORD=ubuntu

    working_directory: /tmp/project

    steps:
      - attach_workspace:
          at: /tmp/project/workspace

      - run: sudo docker-php-ext-install mysqli pdo pdo_mysql
      - run: cd /tmp/project/repo && php build/phpunit/mysql_setup.php
      - run: cd /tmp/project/repo && php vendor/bin/phpunit --coverage-clover build/coverage/xml
      - run: cd /tmp/project/repo && php vendor/bin/codacycoverage clover build/coverage/xml

  python-test:
    machine:
      enabled: true

    working_directory: /tmp/project

    steps:
      - attach_workspace:
          at: /tmp/project/workspace

      - run: cd /tmp/project/repo && python2.7 ./build/tests/filenames.py www
      - run: cd /tmp/project/repo && python2.7 ./build/tests/existence.py www
      - run: cd /tmp/project/repo && sh ./build/tests/line-endings.sh

  deploy-testing:
    machine:
      enabled: true

    working_directory: /tmp/project

    steps:
      - attach_workspace:
          at: /tmp/project/workspace

      - run: cd /tmp/project/repo/www/ && scp -oStrictHostKeyChecking=no -r * mentor@compcamps.com:/home/mentor/public_html/testing
      - run: cd /tmp/project/repo/www/ && scp -oStrictHostKeyChecking=no -r .htaccess mentor@compcamps.com:/home/mentor/public_html/testing
      - run: cd /tmp/project/repo/www/ && scp -oStrictHostKeyChecking=no -r dash/.htaccess mentor@compcamps.com:/home/mentor/public_html/testing/dash

  deploy-live:
    machine:
      enabled: true

    working_directory: /tmp/project

    steps:
      - attach_workspace:
          at: /tmp/project/workspace

      - run: cd /tmp/project/repo/www/ && scp -oStrictHostKeyChecking=no -r * mentor@compcamps.com:/home/mentor/public_html/
      - run: cd /tmp/project/repo/www/ && scp -oStrictHostKeyChecking=no -r .htaccess.live mentor@compcamps.com:/home/mentor/public_html/.htaccess
      - run: cd /tmp/project/repo/www/ && scp -oStrictHostKeyChecking=no -r dash/.htaccess.live mentor@compcamps.com:/home/mentor/public_html/dash/.htaccess

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - php-test:
          requires:
            - build
      - python-test:
          requires:
            - build
      - deploy-testing:
          requires:
            - python-test
            - php-test
          filters:
            branches:
              only: master
      - deploy-live:
          requires:
            - python-test
            - php-test
          filters:
            branches:
              only: live
